language: java

addons:
    sonarcloud:
        organization: "leo27h-github"
        token:
            secure: rGWnrUrMlZUA8DXH5dXWJiqgBy4K5B1T5D018soCIL+UJGsjNsut63f7kXn1BK5KIkyAT11B8b7pHpE/Q4R+vVtugvDnuW/SXp9pNlanTP6+kPq1u4V1UKtxJAGnKJxaBlnikHI1HCWZDX01oGlwqo3YHQbRfxMZqGpGq9IxEZYyEUoj3HSlZS69FSQ1NDp8Q6VJFwzqqCAaEbvUVkYSqAhetJoxWGyf6HgBO2SSVdAnd8ycrZQznyHOS8lNu7oIdBMRvpkZPFzuazBeH6EWG0qXVbjtyPpXk6fVfF0BQOMkdkRXl68jOMJgEtn243zN+3I3bOBAuAl9SIheTNvfck8S4NAHY8YHVIt3J8gExtULFdWo2eLoubweyWGkwbdi7jfo76L6yT+tlN5BbEganHb31QiwuhTswE4jXVAY8tQlJevBc6t7SFbSOmYoHgHCcGE0B4FtkMKpBCkx/S9FA9z9enscgVsXOmMUydKagccFpbQSk99JNmW8BlLiiVhIaJMz3yIGCWPscM3rkc+ugtsW+fEnw8kjU92VkIIPeKOoBrTS7yAK//KS1+ue3HEPOMY7dUSQBrit8miRUlmZsc7zzE19JrLZSAy25ZjWmQWcb6lvikSspi01ngbEFsFnTWA1bjjXZW3a+M59MwjB/+QvkmzllkQ2/jRmYTqwmkc=
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar